### PR TITLE
Updated XML defaults and edited vignettes

### PR DESCRIPTION
**Pull request by brendensm**
The following commits:
- Fix the package so that the natality data sets can be queried (D10, D27, D66, D149).
- Edits the titles of the vignettes so that they will build if requested on installation.
- Edits the README, vignettes, dbnamelookup, so that the most recent D66 name is up to date.
- Makes small changes to the description to update the version of roxygen, adding the rlang dependency.

### CODE REVIEW

**Comment by jtr13** [comment]
Thanks so much, this is awesome! I got stuck on updating the default query lists -- did you get them directly from the CDC?

**Comment by brendensm** [comment]
Yes! I downloaded the query list right from the web interface. I'm not sure what changes specifically did it, but I made sure our lists matched each one I downloaded.

**Comment by jtr13** [comment]
Could you share the link to the query lists? I worked with default query lists that someone at the CDC emailed me, and they kept getting out of date really quickly.

There are still problems with the order of the group by variables and the limiting parameters in general. When I get a chance I'll open a new issue.

**Comment by brendensm** [comment]
When I emailed the folks at wonder, they directly me to submit a query through the interface for an example XML request. Here is their language:

"To download example XML query parameters for any specific request, after the results to your query are display in the Results tab, then click the “API Options” button below the tabs, to open a dialog that offers you the specific request and results in XML format.  You can use the “request” file as a template for posting the query via the API."

For this, I went to each natality data base and submitted a blank request, only grouping by year. Then I downloaded the XML per the email's instructions.

**Comment by jtr13** [comment]
This is amazing... I wonder if it's always been there or it's a new option.

**Comment by brendensm** [comment]
I'm not sure, but I'm glad I emailed! It makes life much easier.

**Comment by jtr13** [comment]
I made some updates to a function `send_query()` that I was mostly using for testing but might be very helpful esp if queries with `getData()` aren't working properly. It makes the query request directly from the exported `.xml` file. See the readme or Intro vignette. If you do check it out, feedback welcome.

**Comment by jtr13** [comment]
@brendensm Hi there! Might you be interested in becoming the maintainer of this package with full rights, basically take over this package?

**Comment by brendensm** [comment]
@jtr13 Hello! Sorry it has been some time since this comment. I would definitely be interested in taking over the package. That isn't a process I am super familiar with. Do you know how transferring a repo works?

**Comment by jtr13** [comment]
@brendensm Fantastic! I really wish I had more time to devote to it, but sadly I do not. My understanding is that repos aren't typically moved. Particularly since this is setup on an organization account rather than my personal one I think we should leave it here. I can add you as a collaborator and then you can add yourself to the DESCRIPTION file as author and creator "aut", "cre" the term used for maintainers. How does that sound? To be clear, you'll have free reign, nothing will need to be checked with me.

**Comment by brendensm** [comment]
That sounds great to me! I appreciate all of your work and contributions to this project thus far. Hopefully I can serve it well. I think it would be great to get a stable version up on CRAN.

**Comment by jtr13** [comment]
A CRAN version would be amazing! I just added you as a collaborator with "Maintain" privileges.

**Pull request merged**
